apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::791272971151:role/eksctl-rosboshop-dev-nodegroup-rob-NodeInstanceRole-bhpp8qQOVP0X
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::791272971151:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-12T10:58:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1252"
  uid: c09d3f2b-b1e9-4d7a-9582-79068628e7de
