apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::791272971151:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-xqp5r2YyFrR7
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::791272971151:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-13T10:51:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1151"
  uid: 380746d5-bdf3-4cf8-9d2a-980582931b9e

